export const studyData = {
  overview: {
    title: "Visão Geral e Estratégia",
    intro:
      "Bem-vindo(a) ao seu centro de comando. Aqui você encontra a filosofia por trás do seu plano de estudos e as ferramentas para visualizar a estratégia. O sucesso no ENEM começa com um plano inteligente, focado na Teoria de Resposta ao Item (TRI).",
    strategyMatrix: {
      labels: [
        "Interpretação de Textos",
        "Proporcionalidade",
        "Funções da Linguagem",
        "Operações Básicas",
        "Ecologia",
        "Análise de Gráficos",
        "Química Básica",
        "Física Básica",
        "Brasil Colônia/Império",
        "Era Vargas",
        "Cinemática",
        "Estatística",
        "Geometria Plana",
        "Urbanização",
        "Eletrodinâmica",
        "Análise Combinatória",
      ],
      datasets: [
        {
          label: "Incidência na Prova",
          data: [
            10, 9.8, 8.5, 9.5, 9.2, 8.8, 7, 6.8, 8.7, 8.6, 7.5, 8.4, 8.3, 8.2,
            7.8, 6.5,
          ],
          backgroundColor: "rgba(58, 134, 255, 0.6)",
        },
        {
          label: "Amigabilidade-TRI (Facilidade)",
          data: [
            10, 9.8, 9.5, 10, 8, 9.2, 9, 9.1, 7, 7.2, 6.5, 7.8, 6.8, 7.5, 5.5,
            4,
          ],
          backgroundColor: "rgba(255, 159, 64, 0.6)",
        },
      ],
    },
  },
  schedule: {
    title: "Cronograma Semanal Interativo",
    intro:
      "Selecione a semana para ver seu plano de estudos diário. Use os botões ✨ para gerar questões e aprofundar seu conhecimento com a ajuda da IA. Clique no link da videoaula para um reforço visual do conteúdo.",
    weeks: [
      {
        focus: "Fundamentos de Matemática e Linguagens",
        days: [
          {
            day: "Segunda",
            subject: "Matemática",
            content: "As 4 operações básicas e expressões numéricas",
            activity: "Teoria (45 min) + 15 exercícios (45 min).",
            videoTitle: "OPERAÇÕES FUNDAMENTAIS | Aula 1",
            videoUrl: "https://www.youtube.com/watch?v=b_f3yMAgI2A",
          },
          {
            day: "Terça",
            subject: "Linguagens",
            content: "Tipologia e Gêneros Textuais",
            activity: "Teoria (45 min) + Prática de identificação (45 min).",
            videoTitle: "TIPOS TEXTUAIS (NARRAÇÃO, DESCRIÇÃO...)",
            videoUrl: "https://www.youtube.com/watch?v=acP0-IqW3sU",
          },
          {
            day: "Quarta",
            subject: "Matemática",
            content: "Frações e Operações com Frações",
            activity: "Teoria (45 min) + 15 exercícios (45 min).",
            videoTitle: "Tudo sobre FRAÇÕES em 25 Minutos!",
            videoUrl: "https://www.youtube.com/watch?v=83fCNGgDkMU",
          },
          {
            day: "Quinta",
            subject: "Linguagens",
            content: "Elementos da Comunicação e Funções da Linguagem",
            activity: "Teoria (45 min) + Análise de tirinhas (45 min).",
            videoTitle: "FUNÇÕES DA LINGUAGEM",
            videoUrl: "https://www.youtube.com/watch?v=9i_M5-_65pU",
          },
          {
            day: "Sexta",
            subject: "Redação",
            content: "Entendendo a Estrutura Dissertativo-Argumentativa",
            activity:
              "Assistir vídeos sobre a função de cada parágrafo (90 min).",
            videoTitle: "A ESTRUTURA DA REDAÇÃO DO ENEM",
            videoUrl: "https://www.youtube.com/watch?v=u8Qdfj_f_vE",
          },
          {
            day: "Sábado",
            subject: "Prática e Introdução",
            content:
              "Manhã (3h): 40 exercícios de Matemática. Tarde (2h): Introdução à Biologia (Níveis de organização, Ecologia básica).",
            activity: "Resolução e leitura.",
            videoTitle: "INTRODUÇÃO À ECOLOGIA",
            videoUrl: "https://www.youtube.com/watch?v=y9d-19n-d_E",
          },
          {
            day: "Domingo",
            subject: "Redação #1 e Simulado #1",
            content:
              "Redação sobre educação digital. Simulado (30Q) e Correção Ativa.",
            activity: "Escrita, resolução e análise.",
            videoTitle: "",
            videoUrl: "",
          },
        ],
      },
      {
        focus: "Avançando nos Fundamentos e Introduzindo Ciências",
        days: [
          {
            day: "Segunda",
            subject: "Matemática",
            content: "Porcentagem",
            activity: "Teoria (45 min) + 15 exercícios (45 min).",
            videoTitle: "Aprenda PORCENTAGEM de uma vez por todas!",
            videoUrl: "https://www.youtube.com/watch?v=ZZqgVOH_sS4",
          },
          {
            day: "Terça",
            subject: "Linguagens",
            content: "Identificação de Tese e Argumentos",
            activity: "Teoria (45 min) + Prática em textos (45 min).",
            videoTitle: "COMO ACHAR A TESE DE UM TEXTO?",
            videoUrl: "https://www.youtube.com/watch?v=YgPZ-t0-YwY",
          },
          {
            day: "Quarta",
            subject: "Matemática",
            content: "Regra de 3 Simples e Composta",
            activity: "Teoria (45 min) + 15 exercícios (45 min).",
            videoTitle: "REGRA DE 3: SIMPLES E COMPOSTA",
            videoUrl: "https://www.youtube.com/watch?v=P1L1B-V7a3w",
          },
          {
            day: "Quinta",
            subject: "Química",
            content: "Matéria, substâncias e misturas",
            activity: "Teoria (45 min) + 10 exercícios (45 min).",
            videoTitle: "SUBSTÂNCIAS E MISTURAS",
            videoUrl: "https://www.youtube.com/watch?v=QCX_G3T2Z5c",
          },
          {
            day: "Sexta",
            subject: "Física",
            content: "Notação Científica e Ordem de Grandeza",
            activity: "Teoria (45 min) + 10 exercícios (45 min).",
            videoTitle: "Notação Científica e Ordem de Grandeza",
            videoUrl: "https://www.youtube.com/watch?v=Lg-qQyY-aT4",
          },
          {
            day: "Sábado",
            subject: "Prática e Revisão",
            content:
              "Manhã (3h): 30 exercícios (Mat/Qui/Fis). Tarde (2h): Revisar temas da Semana 1.",
            activity: "Resolução e revisão ativa.",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Domingo",
            subject: "Redação #2 e Simulado #2",
            content:
              "Redação sobre vacinação. Simulado (35Q) e Correção Ativa.",
            activity: "Escrita, resolução e análise.",
            videoTitle: "",
            videoUrl: "",
          },
        ],
      },
      {
        focus: "Consolidando Fundamentos e Humanas",
        days: [
          {
            day: "Segunda",
            subject: "Matemática",
            content: "Potenciação e Radiciação",
            activity: "Teoria (45 min) + 15 exercícios (45 min).",
            videoTitle: "POTENCIAÇÃO E RADICIAÇÃO",
            videoUrl: "https://www.youtube.com/watch?v=iT-a_Tq_lA4",
          },
          {
            day: "Terça",
            subject: "Linguagens",
            content: "Figuras de Linguagem",
            activity:
              "Teoria (45 min) + 10 exercícios de identificação (45 min).",
            videoTitle: "FIGURAS DE LINGUAGEM",
            videoUrl: "https://www.youtube.com/watch?v=OhG-533j1iI",
          },
          {
            day: "Quarta",
            subject: "História",
            content: "Fontes Históricas e Periodização",
            activity: "Teoria (45 min) + Análise de fontes (45 min).",
            videoTitle: "FONTES HISTÓRICAS E PERIODIZAÇÃO",
            videoUrl: "https://www.youtube.com/watch?v=o0yq_mG2j2A",
          },
          {
            day: "Quinta",
            subject: "Geografia",
            content: "Conceitos da Geografia e Introdução à Cartografia",
            activity: "Teoria (45 min) + 10 exercícios (45 min).",
            videoTitle: "INTRODUÇÃO À CARTOGRAFIA",
            videoUrl: "https://www.youtube.com/watch?v=DbB0a22LpWw",
          },
          {
            day: "Sexta",
            subject: "Revisão Ativa",
            content: "Revisar caderno de erros das semanas 1 e 2",
            activity: "Refazer 10 questões erradas (90 min).",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Sábado",
            subject: "Prática Intensiva",
            content:
              "Manhã (3h): 40 exercícios (Mat/Ling/Hist/Geo). Tarde (2h): Aprofundar em Cartografia (escalas).",
            activity: "Resolução de exercícios.",
            videoTitle: "ESCALA CARTOGRÁFICA",
            videoUrl: "https://www.youtube.com/watch?v=03puUq5y6yM",
          },
          {
            day: "Domingo",
            subject: "Redação #3 e Simulado #3",
            content:
              "Redação sobre fake news. Simulado (40Q) e Correção Ativa.",
            activity: "Escrita, resolução e análise.",
            videoTitle: "",
            videoUrl: "",
          },
        ],
      },
      {
        focus: "Revisão da Fundação e Variação Linguística",
        days: [
          {
            day: "Segunda",
            subject: "Matemática",
            content: "Revisão: Porcentagem e Regra de 3",
            activity: "20 exercícios de fixação (90 min).",
            videoTitle: "REVISÃO: REGRA DE 3 E PORCENTAGEM",
            videoUrl: "https://www.youtube.com/watch?v=P1L1B-V7a3w",
          },
          {
            day: "Terça",
            subject: "Linguagens",
            content: "Variação Linguística (Social, Regional, Histórica)",
            activity: "Teoria (45 min) + 10 exercícios (45 min).",
            videoTitle: "VARIAÇÃO LINGUÍSTICA",
            videoUrl: "https://www.youtube.com/watch?v=qjHflg_vS3Y",
          },
          {
            day: "Quarta",
            subject: "Química e Física",
            content: "Revisão: Misturas e Notação Científica",
            activity: "20 exercícios (10 de cada) (90 min).",
            videoTitle: "REVISÃO: QUÍMICA E FÍSICA",
            videoUrl: "https://www.youtube.com/watch?v=Lg-qQyY-aT4",
          },
          {
            day: "Quinta",
            subject: "Humanas",
            content: "Revisão: Periodização Histórica e Cartografia",
            activity: "Releitura e 10 exercícios (90 min).",
            videoTitle: "REVISÃO: HISTÓRIA E GEOGRAFIA",
            videoUrl: "https://www.youtube.com/watch?v=DbB0a22LpWw",
          },
          {
            day: "Sexta",
            subject: "Redação",
            content: "Análise da Competência 1 (Gramática) e 4 (Coesão)",
            activity: "Corrigir erros gramaticais de textos antigos (90 min).",
            videoTitle: "COESÃO E COERÊNCIA",
            videoUrl: "https://www.youtube.com/watch?v=2YJk_b2cqD0",
          },
          {
            day: "Sábado",
            subject: "Prática Geral",
            content:
              "Manhã (3h): Lista com 30 exercícios variados da Fase 1. Tarde (2h): Leitura de atualidades.",
            activity: "Resolução e leitura.",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Domingo",
            subject: "Redação #4 e Simulado #4",
            content:
              "Redação sobre lixo eletrônico. Simulado (45Q) e Correção Ativa.",
            activity: "Escrita, resolução e análise.",
            videoTitle: "",
            videoUrl: "",
          },
        ],
      },
      {
        focus: "Ecologia, Brasil Colônia e Análise de Gráficos",
        days: [
          {
            day: "Segunda",
            subject: "Biologia",
            content: "Relações Ecológicas Harmônicas e Desarmônicas",
            activity: "Teoria (50 min) + 10 exercícios (40 min).",
            videoTitle: "RELAÇÕES ECOLÓGICAS",
            videoUrl: "https://www.youtube.com/watch?v=1-u51_yJ3xM",
          },
          {
            day: "Terça",
            subject: "História",
            content: "Brasil Colônia: Economia Açucareira e Sociedade",
            activity: "Teoria (50 min) + Leitura de textos de época (40 min).",
            videoTitle: "BRASIL COLÔNIA: ECONOMIA AÇUCAREIRA",
            videoUrl: "https://www.youtube.com/watch?v=y3eJ4w2-A3I",
          },
          {
            day: "Quarta",
            subject: "Matemática",
            content: "Análise de Gráficos e Tabelas",
            activity: "Teoria (40 min) + 15 exercícios práticos (50 min).",
            videoTitle: "ANÁLISE DE GRÁFICOS E TABELAS",
            videoUrl: "https://www.youtube.com/watch?v=nL0y1g_I7A4",
          },
          {
            day: "Quinta",
            subject: "Linguagens",
            content: "Interpretação: Identificar tese em textos complexos",
            activity: "Prática em artigos de opinião (90 min).",
            videoTitle: "INTERPRETAÇÃO DE TEXTOS",
            videoUrl: "https://www.youtube.com/watch?v=b0S82-Vf5yU",
          },
          {
            day: "Sexta",
            subject: "Química",
            content: "Modelos Atômicos e Tabela Periódica",
            activity: "Teoria (50 min) + 10 exercícios (40 min).",
            videoTitle: "MODELOS ATÔMICOS E TABELA PERIÓDICA",
            videoUrl: "https://www.youtube.com/watch?v=sOnoA_rQd8g",
          },
          {
            day: "Sábado",
            subject: "Prática e Aprofundamento",
            content:
              "Manhã (3h): 40 exercícios dos temas da semana. Tarde (2h): Geografia: Urbanização e Problemas Urbanos.",
            activity: "Resolução e teoria.",
            videoTitle: "URBANIZAÇÃO NO BRASIL",
            videoUrl: "https://www.youtube.com/watch?v=c0OAZm5uAFbI",
          },
          {
            day: "Domingo",
            subject: "Redação #5 e Simulado #5",
            content:
              "Redação sobre trabalho escravo. Simulado (50Q) e Correção Ativa.",
            activity: "Escrita, resolução e análise.",
            videoTitle: "",
            videoUrl: "",
          },
        ],
      },
      {
        focus: "Alta Frequência: MUV, Estatística e Violência",
        days: [
          {
            day: "Segunda",
            subject: "Física",
            content: "Cinemática: Movimento Uniforme (MU) e MUV",
            activity: "Teoria e fórmulas (50 min) + 10 exercícios (40 min).",
            videoTitle: "CINEMÁTICA: MU E MUV",
            videoUrl: "https://www.youtube.com/watch?v=j2-TH_WJpCQ",
          },
          {
            day: "Terça",
            subject: "Matemática",
            content: "Estatística: Média, Moda e Mediana",
            activity: "Teoria (40 min) + 15 exercícios (50 min).",
            videoTitle: "ESTATÍSTICA: MÉDIA, MODA E MEDIANA",
            videoUrl: "https://www.youtube.com/watch?v=ttYv92f4Q2I",
          },
          {
            day: "Quarta",
            subject: "História",
            content: "Brasil Império: Primeiro e Segundo Reinado",
            activity: "Teoria (50 min) + 10 exercícios (40 min).",
            videoTitle: "BRASIL IMPÉRIO",
            videoUrl: "https://www.youtube.com/watch?v=mYtFNHa0_Kk",
          },
          {
            day: "Quinta",
            subject: "Geografia",
            content: "Problemas Ambientais Urbanos e Rurais",
            activity: "Teoria (50 min) + 10 exercícios (40 min).",
            videoTitle: "IMPACTOS AMBIENTAIS",
            videoUrl: "https://www.youtube.com/watch?v=YfP_P_3qP-o",
          },
          {
            day: "Sexta",
            subject: "Revisão Espaçada",
            content: "Revisar caderno de erros das semanas 1-3",
            activity: "Refazer 10 questões erradas (90 min).",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Sábado",
            subject: "Prática Intensiva",
            content:
              "Manhã (3h): 50 exercícios dos temas da semana. Tarde (2h): Biologia: Desequilíbrios Ambientais.",
            activity: "Resolução e teoria.",
            videoTitle: "DESEQUILÍBRIOS AMBIENTAIS",
            videoUrl: "https://www.youtube.com/watch?v=Yt2sXAltuCo",
          },
          {
            day: "Domingo",
            subject: "Redação #6 e Simulado #6",
            content:
              "Redação sobre violência contra a mulher. Simulado (60Q) e Correção Ativa.",
            activity: "Escrita, resolução e análise.",
            videoTitle: "",
            videoUrl: "",
          },
        ],
      },
      {
        focus: "Geometria Plana e Era Vargas",
        days: [
          {
            day: "Segunda",
            subject: "Matemática",
            content: "Geometria Plana: Áreas e Perímetros",
            activity: "Teoria e fórmulas (50 min) + 12 exercícios (40 min).",
            videoTitle: "GEOMETRIA PLANA: ÁREAS",
            videoUrl: "https://www.youtube.com/watch?v=Jn_TTB8eKSc",
          },
          {
            day: "Terça",
            subject: "História",
            content: "Era Vargas",
            activity: "Teoria (50 min) + análise de documentos (40 min).",
            videoTitle: "ERA VARGAS",
            videoUrl: "https://www.youtube.com/watch?v=L2q2qi-2p8c",
          },
          {
            day: "Quarta",
            subject: "Química",
            content: "Ligações Químicas (Iônica, Covalente, Metálica)",
            activity: "Teoria (50 min) + 15 exercícios (40 min).",
            videoTitle: "LIGAÇÕES QUÍMICAS",
            videoUrl: "https://www.youtube.com/watch?v=aGZz-4aH6hY",
          },
          {
            day: "Quinta",
            subject: "Linguagens",
            content: "Intertextualidade e Paráfrase",
            activity: "Teoria e prática com textos e músicas (90 min).",
            videoTitle: "INTERTEXTUALIDADE",
            videoUrl: "https://www.youtube.com/watch?v=4igZi_aWSt0",
          },
          {
            day: "Sexta",
            subject: "Redação",
            content: "Análise da Competência 3 (Argumentação)",
            activity:
              "Revisar a força dos argumentos dos seus textos (90 min).",
            videoTitle: "COMPETÊNCIA 3 REDAÇÃO ENEM",
            videoUrl: "https://www.youtube.com/watch?v=zGkXIEwQQ-M",
          },
          {
            day: "Sábado",
            subject: "Prática e Revisão",
            content:
              "Manhã (3h): 40 exercícios da semana. Tarde (2h): Revisar Ecologia.",
            activity: "Resolução e revisão.",
            videoTitle: "REVISÃO ECOLOGIA",
            videoUrl: "https://www.youtube.com/watch?v=y9d-19n-d_E",
          },
          {
            day: "Domingo",
            subject: "Redação #7 e Simulado #7",
            content:
              "Redação sobre saúde mental. Simulado (60Q) e Correção Ativa.",
            activity: "Escrita, resolução e análise.",
            videoTitle: "",
            videoUrl: "",
          },
        ],
      },
      {
        focus: "Termoquímica e Proposta de Intervenção",
        days: [
          {
            day: "Segunda",
            subject: "Química",
            content: "Termoquímica: Entalpia e Leis",
            activity: "Teoria (60 min) + 10 exercícios (30 min).",
            videoTitle: "TERMOQUÍMICA",
            videoUrl: "https://www.youtube.com/watch?v=yUn90-2y-qk",
          },
          {
            day: "Terça",
            subject: "Matemática",
            content: "Geometria Espacial: Prismas e Cilindros",
            activity: "Teoria (50 min) + 10 exercícios (40 min).",
            videoTitle: "GEOMETRIA ESPACIAL: PRISMAS E CILINDROS",
            videoUrl: "https://www.youtube.com/watch?v=IeTSv_a-aI4",
          },
          {
            day: "Quarta",
            subject: "Física",
            content: "Leis de Newton e Aplicações",
            activity: "Teoria (50 min) + 12 exercícios (40 min).",
            videoTitle: "LEIS DE NEWTON",
            videoUrl: "https://www.youtube.com/watch?v=Z1hrv_D-5pM",
          },
          {
            day: "Quinta",
            subject: "Biologia",
            content: "Citologia: Membrana e Organelas",
            activity: "Teoria (50 min) + 10 exercícios (40 min).",
            videoTitle: "CITOLOGIA: ORGANELAS",
            videoUrl: "https://www.youtube.com/watch?v=uD_Qd-B3s4g",
          },
          {
            day: "Sexta",
            subject: "Redação",
            content: "Competência 5: Esboço da Proposta de Intervenção (PI)",
            activity: "Praticar a criação de PIs para temas antigos (90 min).",
            videoTitle: "PROPOSTA DE INTERVENÇÃO",
            videoUrl: "https://www.youtube.com/watch?v=R59s00i2L5M",
          },
          {
            day: "Sábado",
            subject: "Prática Intensiva",
            content:
              "Manhã (3h): 40 exercícios da semana. Tarde (2h): Revisar Brasil Colônia/Império.",
            activity: "Resolução e revisão.",
            videoTitle: "REVISÃO BRASIL COLÔNIA E IMPÉRIO",
            videoUrl: "https://www.youtube.com/watch?v=mYtFNHa0_Kk",
          },
          {
            day: "Domingo",
            subject: "Redação #8 e Simulado #8",
            content:
              "Redação sobre segurança alimentar. Simulado (70Q) e Correção Ativa.",
            activity: "Escrita, resolução e análise.",
            videoTitle: "",
            videoUrl: "",
          },
        ],
      },
      {
        focus: "Revisão Gramatical e Humanas",
        days: [
          {
            day: "Segunda",
            subject: "Linguagens",
            content: "Revisão Ortográfica e Gramatical",
            activity:
              "Focar nos erros da Competência 1 das suas redações (90 min).",
            videoTitle: "ERROS DE GRAMÁTICA NA REDAÇÃO",
            videoUrl: "https://www.youtube.com/watch?v=e_k0Ie-sPaE",
          },
          {
            day: "Terça",
            subject: "História",
            content: "Ditadura Militar no Brasil",
            activity:
              "Teoria (50 min) + análise de músicas de protesto (40 min).",
            videoTitle: "DITADURA MILITAR NO BRASIL",
            videoUrl: "https://www.youtube.com/watch?v=b21cnjN4d9s",
          },
          {
            day: "Quarta",
            subject: "Geografia",
            content: "Fontes de Energia e Indústria no Brasil",
            activity: "Teoria (50 min) + 10 exercícios (40 min).",
            videoTitle: "FONTES DE ENERGIA",
            videoUrl: "https://www.youtube.com/watch?v=333QpP8P0sU",
          },
          {
            day: "Quinta",
            subject: "Revisão Matemática",
            content: "Revisar Geometria Plana e Estatística",
            activity: "20 exercícios dos temas (90 min).",
            videoTitle: "REVISÃO GEOMETRIA E ESTATÍSTICA",
            videoUrl: "https://www.youtube.com/watch?v=ttYv92f4Q2I",
          },
          {
            day: "Sexta",
            subject: "Revisão Natureza",
            content: "Revisar Leis de Newton e Ligações Químicas",
            activity: "20 exercícios dos temas (90 min).",
            videoTitle: "REVISÃO FÍSICA E QUÍMICA",
            videoUrl: "https://www.youtube.com/watch?v=Z1hrv_D-5pM",
          },
          {
            day: "Sábado",
            subject: "Prática Geral",
            content:
              "Manhã (3h): 40 exercícios variados da Fase 2. Tarde (2h): Leitura de atualidades.",
            activity: "Resolução e leitura.",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Domingo",
            subject: "Redação #9 e Simulado #9",
            content:
              "Revisão ortográfica e gramatical da redação da semana 8. Simulado (70Q) e Correção Ativa.",
            activity: "Reescrita, resolução e análise.",
            videoTitle: "",
            videoUrl: "",
          },
        ],
      },
      {
        focus: "Eletrodinâmica, Orgânica e Detalhando a PI",
        days: [
          {
            day: "Segunda",
            subject: "Física",
            content: "Eletrodinâmica: Circuitos e Leis de Ohm",
            activity: "Teoria (60 min) + 8 exercícios (30 min).",
            videoTitle: "ELETRODINÂMICA: CIRCUITOS",
            videoUrl: "https://www.youtube.com/watch?v=WxY2c2x9y8Y",
          },
          {
            day: "Terça",
            subject: "Química",
            content: "Química Orgânica: Funções Oxigenadas",
            activity:
              "Teoria e nomenclatura (60 min) + 10 exercícios (30 min).",
            videoTitle: "FUNÇÕES OXIGENADAS",
            videoUrl: "https://www.youtube.com/watch?v=9xLz2A4pC-c",
          },
          {
            day: "Quarta",
            subject: "Filosofia",
            content: "Filosofia Antiga: Sócrates e Platão",
            activity: "Teoria (60 min) + Leitura de trecho (30 min).",
            videoTitle: "FILOSOFIA ANTIGA: SÓCRATES E PLATÃO",
            videoUrl: "https://www.youtube.com/watch?v=z4j92_aI3xU",
          },
          {
            day: "Quinta",
            subject: "Matemática",
            content: "Probabilidade (conceitos básicos)",
            activity: "Teoria (60 min) + 8 exercícios (30 min).",
            videoTitle: "PROBABILIDADE",
            videoUrl: "https://www.youtube.com/watch?v=5sY42r4-O_o",
          },
          {
            day: "Sexta",
            subject: "Redação",
            content: "Detalhando a PI: Agente e Ação",
            activity: "Praticar o detalhamento em temas antigos (90 min).",
            videoTitle: "DETALHANDO A PROPOSTA DE INTERVENÇÃO",
            videoUrl: "https://www.youtube.com/watch?v=R59s00i2L5M",
          },
          {
            day: "Sábado",
            subject: "Prática e Sociologia",
            content:
              "Manhã (3h): Prática dos temas da semana. Tarde (3h): Sociologia Clássica (Durkheim, Weber, Marx).",
            activity: "Resolução e teoria.",
            videoTitle: "SOCIOLOGIA CLÁSSICA",
            videoUrl: "https://www.youtube.com/watch?v=O1fenw6A9iI",
          },
          {
            day: "Domingo",
            subject: "Redação #10 e Simulado #10",
            content:
              "Redação sobre IA na educação. Simulado (80Q) e Correção Ativa.",
            activity: "Escrita, resolução e análise.",
            videoTitle: "",
            videoUrl: "",
          },
        ],
      },
      {
        focus: "Ondulatória e Simulado Dia 1",
        days: [
          {
            day: "Segunda",
            subject: "Física",
            content: "Ondulatória: Fenômenos e Equação Fundamental",
            activity: "Teoria (60 min) + 10 exercícios (30 min).",
            videoTitle: "ONDULATÓRIA",
            videoUrl: "https://www.youtube.com/watch?v=tY8vB-5T2yA",
          },
          {
            day: "Terça",
            subject: "Química",
            content: "Estequiometria: Cálculos básicos",
            activity: "Teoria (60 min) + 10 exercícios (30 min).",
            videoTitle: "ESTEQUIOMETRIA",
            videoUrl: "https://www.youtube.com/watch?v=xTf-pD-v30E",
          },
          {
            day: "Quarta",
            subject: "Biologia",
            content: "Genética: Leis de Mendel",
            activity: "Teoria (60 min) + 10 exercícios (30 min).",
            videoTitle: "GENÉTICA: 1ª LEI DE MENDEL",
            videoUrl: "https://www.youtube.com/watch?v=F_qC-dGg-pE",
          },
          {
            day: "Quinta",
            subject: "Matemática",
            content: "Análise Combinatória",
            activity: "Teoria (60 min) + 10 exercícios (30 min).",
            videoTitle: "ANÁLISE COMBINATÓRIA",
            videoUrl: "https://www.youtube.com/watch?v=10j_h4b-x2o",
          },
          {
            day: "Sexta",
            subject: "Redação",
            content: "Detalhando a PI: Meio/Modo e Finalidade",
            activity: "Praticar o detalhamento completo (90 min).",
            videoTitle: "PROPOSTA DE INTERVENÇÃO NOTA 1000",
            videoUrl: "https://www.youtube.com/watch?v=R59s00i2L5M",
          },
          {
            day: "Sábado",
            subject: "Revisão Geral Humanas",
            content:
              "Revisar todo o conteúdo de Humanas através de mapas mentais e 30 questões.",
            activity: "Revisão e prática.",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Domingo",
            subject: "Redação #11 e Simulado #11",
            content:
              "Redação sobre sustentabilidade. Simulado Dia 1 (90Q) e Correção Ativa.",
            activity: "Escrita, resolução e análise.",
            videoTitle: "",
            videoUrl: "",
          },
        ],
      },
      {
        focus: "Eletromagnetismo e Simulado Dia 2",
        days: [
          {
            day: "Segunda",
            subject: "Física",
            content: "Eletromagnetismo: Indução e Força",
            activity: "Teoria (60 min) + 8 exercícios (30 min).",
            videoTitle: "ELETROMAGNETISMO",
            videoUrl: "https://www.youtube.com/watch?v=wXwzVdJ8n0U",
          },
          {
            day: "Terça",
            subject: "Química",
            content: "Soluções: Concentração e Diluição",
            activity: "Teoria (60 min) + 10 exercícios (30 min).",
            videoTitle: "SOLUÇÕES: CONCENTRAÇÃO E DILUIÇÃO",
            videoUrl: "https://www.youtube.com/watch?v=e_F9-cz_eAE",
          },
          {
            day: "Quarta",
            subject: "Biologia",
            content: "Evolução: Darwinismo e Neodarwinismo",
            activity: "Teoria (60 min) + 10 exercícios (30 min).",
            videoTitle: "EVOLUÇÃO: DARWINISMO E NEODARWINISMO",
            videoUrl: "https://www.youtube.com/watch?v=ek7sGa-lS2Y",
          },
          {
            day: "Quinta",
            subject: "Matemática",
            content: "Logaritmos: Propriedades e Equações",
            activity: "Teoria (60 min) + 10 exercícios (30 min).",
            videoTitle: "LOGARITMOS",
            videoUrl: "https://www.youtube.com/watch?v=jGXaWPrS_gU",
          },
          {
            day: "Sexta",
            subject: "Redação",
            content: "Competência 5: O 'Detalhamento'",
            activity: "Garantir o 5º elemento da PI (90 min).",
            videoTitle: "O DETALHAMENTO NA PROPOSTA DE INTERVENÇÃO",
            videoUrl: "https://www.youtube.com/watch?v=R59s00i2L5M",
          },
          {
            day: "Sábado",
            subject: "Revisão Geral Natureza e Matemática",
            content: "Revisar através de mapas mentais e 40 questões.",
            activity: "Revisão e prática.",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Domingo",
            subject: "Redação #12 e Simulado #12",
            content:
              "Redação sobre privacidade. Simulado Dia 2 (90Q) e Correção Ativa.",
            activity: "Escrita, resolução e análise.",
            videoTitle: "",
            videoUrl: "",
          },
        ],
      },
      {
        focus: "Simulado Completo e Gestão de Tempo",
        days: [
          {
            day: "Segunda",
            subject: "Revisão",
            content: "Revisar caderno de erros dos simulados 11 e 12",
            activity: "Refazer as questões erradas (90 min).",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Terça",
            subject: "Revisão",
            content: "Revisar as fórmulas mais importantes de Exatas",
            activity: "Criar um 'formulário de emergência' (90 min).",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Quarta",
            subject: "Revisão",
            content: "Revisar os conceitos mais importantes de Humanas",
            activity: "Leitura rápida de resumos (90 min).",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Quinta",
            subject: "Revisão",
            content: "Revisar os conceitos mais importantes de Natureza",
            activity: "Leitura rápida de resumos (90 min).",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Sexta",
            subject: "Redação",
            content:
              "Análise da redação da semana 12. Foco: Todas as 5 competências.",
            activity: "Autoavaliação (90 min).",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Sábado",
            subject: "Descanso Leve",
            content: "Organizar material para o simulado.",
            activity: "Sem estudos densos.",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Domingo",
            subject: "Redação #13 e Simulado #13",
            content:
              "Redação sobre distúrbios alimentares. Simulado Completo (180Q) e Correção Ativa.",
            activity: "Prova completa!",
            videoTitle: "",
            videoUrl: "",
          },
        ],
      },
      {
        focus: "Segundo Simulado Completo e Ajustes Finais",
        days: [
          {
            day: "Segunda",
            subject: "Correção",
            content: "Correção Ativa do Simulado 13 (Dia 1)",
            activity: "Focar nos erros de Linguagens e Humanas (90 min).",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Terça",
            subject: "Correção",
            content: "Correção Ativa do Simulado 13 (Dia 2)",
            activity: "Focar nos erros de Natureza e Matemática (90 min).",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Quarta",
            subject: "Redação",
            content: "Gestão do tempo: Rascunho vs. Passar a limpo",
            activity:
              "Treinar passar a limpo um texto antigo em menos de 25 min.",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Quinta",
            subject: "Estratégia",
            content: "Definir estratégia de prova: por onde começar?",
            activity: "Planejar sua ordem de resolução (90 min).",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Sexta",
            subject: "Descanso",
            content: "Descanso pré-simulado",
            activity: "Filme, série, relaxar.",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Sábado",
            subject: "Descanso Leve",
            content: "Organizar material para o simulado.",
            activity: "Sem estudos densos.",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Domingo",
            subject: "Redação #14 e Simulado #14",
            content:
              "Redação sobre evasão escolar. Simulado Completo (180Q) e Correção Ativa.",
            activity: "Prova completa!",
            videoTitle: "",
            videoUrl: "",
          },
        ],
      },
      {
        focus: "Revisão Final e Controle Emocional",
        days: [
          {
            day: "Segunda",
            subject: "Revisão Rápida",
            content: "Revisar fórmulas de Matemática e Física",
            activity: "Releitura do formulário (90 min).",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Terça",
            subject: "Revisão Rápida",
            content: "Revisar conceitos-chave de Biologia e Química",
            activity: "Releitura de mapas mentais (90 min).",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Quarta",
            subject: "Revisão Rápida",
            content: "Revisar conceitos-chave de História e Geografia",
            activity: "Releitura de mapas mentais (90 min).",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Quinta",
            subject: "Revisão Rápida",
            content: "Revisar conceitos-chave de Filosofia e Sociologia",
            activity: "Releitura de mapas mentais (90 min).",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Sexta",
            subject: "Redação e Preparo",
            content:
              "Reler a melhor redação e a estrutura da PI. Organizar material para a prova.",
            activity: "Preparação final.",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Sábado",
            subject: "DESCANSO TOTAL",
            content: "Hidratação, alimentação leve, sono.",
            activity: "Proibido estudar.",
            videoTitle: "",
            videoUrl: "",
          },
          {
            day: "Domingo",
            subject: "PROVA DIA 1",
            content: "Linguagens, Humanas e Redação",
            activity: "Confie no seu preparo!",
            videoTitle: "",
            videoUrl: "",
          },
        ],
      },
    ],
  },
  progress: {
    title: "Progresso em Redação e Simulados",
    intro:
      "Acompanhe sua evolução. Use o botão ✨ para gerar repertório sociocultural para cada tema de redação e turbinar seus textos.",
    milestones: [
      {
        week: 1,
        theme: "Os desafios da educação digital no Brasil",
        skill: "Estrutura (4 parágrafos) e Tese",
        simulation: "30Q",
      },
      {
        week: 2,
        theme: "A importância da vacinação em massa no Brasil",
        skill: "Tópicos Frasais",
        simulation: "35Q",
      },
      {
        week: 3,
        theme: "O combate à desinformação (fake news)",
        skill: "Coesão (conectivos)",
        simulation: "40Q",
      },
      {
        week: 4,
        theme: "Alternativas para o descarte de lixo eletrônico",
        skill: "Revisão Competências 1 e 4",
        simulation: "45Q",
      },
      {
        week: 5,
        theme: "A persistência do trabalho análogo à escravidão",
        skill: "Uso de repertório sociocultural",
        simulation: "50Q",
      },
      {
        week: 6,
        theme: "A persistência da violência contra a mulher",
        skill: "Aprofundamento da argumentação (Comp. 3)",
        simulation: "60Q",
      },
      {
        week: 7,
        theme: "O impacto das redes sociais na saúde mental",
        skill: "Revisão da estrutura argumentativa",
        simulation: "60Q",
      },
      {
        week: 8,
        theme: "Desafios para garantir a segurança alimentar",
        skill: "Esboço da Proposta de Intervenção (PI)",
        simulation: "70Q",
      },
      {
        week: 9,
        theme: "Revisão Ortográfica e Gramatical",
        skill: "Revisão da Competência 1",
        simulation: "70Q",
      },
      {
        week: 10,
        theme: "O papel da IA na transformação da educação",
        skill: "Detalhando a PI: Agente e Ação",
        simulation: "80Q",
      },
      {
        week: 11,
        theme: "Sustentabilidade ambiental nas grandes cidades",
        skill: "Detalhando a PI: Meio/Modo e Finalidade",
        simulation: "90Q (Dia 1)",
      },
      {
        week: 12,
        theme: "Privacidade e segurança nas novas tecnologias",
        skill: "Detalhando a PI: O 'Detalhamento'",
        simulation: "90Q (Dia 2)",
      },
      {
        week: 13,
        theme: "Desafios no combate aos distúrbios alimentares",
        skill: "Foco em todas as 5 competências",
        simulation: "180Q (Completo)",
      },
      {
        week: 14,
        theme: "Evasão escolar e negação do direito à educação",
        skill: "Gestão do tempo e rascunho",
        simulation: "180Q (Completo)",
      },
      {
        week: 15,
        theme: "*Sem redação nova*",
        skill: "Reescrita da redação da semana 14",
        simulation: "*Sem simulado*",
      },
    ],
  },
  resources: {
    title: "Central de Recursos Gratuitos",
    intro:
      "Uma lista curada de canais e plataformas de alta qualidade para apoiar seus estudos.",
    channels: [
      {
        category: "Matemática",
        name: "Professor Ferretto",
        link: "https://www.youtube.com/professorferretto",
      },
      {
        category: "Física",
        name: "Professor Boaro",
        link: "https://www.youtube.com/professoboaro",
      },
      {
        category: "Química",
        name: "Marcelão da Química",
        link: "https://www.youtube.com/MarcelaoDaQuimica",
      },
      {
        category: "Biologia",
        name: "Biologia Total",
        link: "https://www.youtube.com/BiologiaTotal",
      },
      {
        category: "Humanas",
        name: "Parabólica",
        link: "https://www.youtube.com/Parabolica",
      },
      {
        category: "Linguagens",
        name: "Débora Aladim",
        link: "https://www.youtube.com/DeboraAladim",
      },
    ],
    platforms: [
      {
        name: "Repertório Enem",
        description: "Filtro de questões gratuito.",
        link: "https://repertorioenem.com.br/",
      },
      {
        name: "Provas Anteriores do INEP",
        description: "A fonte oficial.",
        link: "https://www.gov.br/inep/pt-br/areas-de-atuacao/avaliacao-e-exames-educacionais/enem/provas-e-gabaritos",
      },
    ],
  },
};
